### ISSUE TITLE
Incompatibility with Eclipse

### ISSUE THREAD

**Issue by fapdash** [EMPRI-DEVOPS/git-privacy#11]
Eclipse / EGit can't commit any more once the post-commit hook has been added to a repository.

![screenshot_78](https://user-images.githubusercontent.com/459631/82720633-da582200-9ca4-11ea-8f4b-424243ab95d9.png)

**Comment by fapdash** [comment]
Correction: the eclipse commit goes through, but the post-commit hook fails. Which kind of is okay, but the error message is still kind of ugly.

**Comment by cburkert** [comment]
Do you have any idea, why egit is still holding the Git lock at that point?

**Comment by fapdash** [comment]
this is a bug in eclipse, I'll work on it: https://bugs.eclipse.org/bugs/show_bug.cgi?id=553428

**Comment by cburkert** [comment]
Nice. Let me know, if this entirely resolves the issue. To me it reads as if it only regards the warning as describing the commit as aborted.

**Comment by fapdash** [comment]
I've implemented the changes for the first bug and tested if it fixes our problem but you where right. It doesn't fix it.
I've opened a detailed bug report here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=566934

**Comment by cburkert** [comment]
Great. Thanks for taking care of that @fapdash

**Comment by cburkert** [comment]
@fapdash The referenced Eclipse bug has been marked as resolved in the meantime. Can you confirm that?

**Comment by fapdash** [comment]
Will be fixed in the next Eclipse release (2021-06), closing.
