### ISSUE TITLE
Save cypher information in the encoded message

### ISSUE THREAD

**Issue by fapdash** [EMPRI-DEVOPS/git-privacy#12]
I think we should save the information about the used cypher, so we can switch algorithms more easily later on without breaking compatibility. Then again, since there are encoded commit dates out there without this, we have to support the version without cypher info moving forward anyway?

**Comment by cburkert** [comment]
The status quo uses libsodiums secret box as wire format, which is widely spread and should be fine for some time. If there arises a need to change the wire format/encryption we'll have to revisit this issue, but for now, as you say, we would have to support the format without explicit cipher indication anyway. I'll close this for now.
