### ISSUE TITLE
Timezone checking fails silently if .gitconfig has quotes around email

### ISSUE THREAD

**Issue by ternarykitten** [EMPRI-DEVOPS/git-privacy#28]
In my git config file, I accidentally put quotes around my `user.email` key. Surprisingly regular Git understands this fine and strips the quotes when committing, but this causes `git-privacy tzcheck` to skip timezone checks altogether.

When `check_timezone_changes()` runs `user_email = cr.get_value("user", "email", "")`, the returned email consists of `'"name@domain.com"'`, where `user_email[0] == user_email[-1] == "`. When calling `repo.iter_commits` and searching for this email, it finds zero results and reaches `if last_commit is None: return False  # no previous commits by this user`. Consequently, timezone leaks are completely ignored with no warning.

There are multiple strategies that could be used to avoid this issue.

One approach is to strip (double, and single too?) quotes around the email using `cr.get_value("user", "email", "").strip('"')`.

Another approach (making leaks more obvious) is to print a warning message on each `return False` branch, like "info: no commits found, using timezone {current_tz} and skipping timezone checks." and "info: no commits found by email {user_email}, using timezone {current_tz} and skipping timezone checks". These messages will only pop up on the first commit made by a user under a repo, and I think they're both useful to explain to users how git-privacy operates (it trusts the first timezone by that user, and warns/errors on different timezones), and as debugging output to make it more obvious when git-privacy is failing to protect timezones (which the user is counting on it doing). Unfortunately, it's trickier than I had hoped to to word the messages in a way that's clear to users.

**Comment by cburkert** [comment]
Thanks for reporting and the great suggestion! GitPython, the library that I use to parse Git configs unfortunately lacks proper support for quoted values. But I will follow your suggestion to work around the issue!

**Comment by cburkert** [comment]
Should be fixed by 357a295. Closing.
@ternarykitten Please re-open if your issue is not fixed.

**Comment by ternarykitten** [comment]
Sorry for the late reply. It works now.
