### ISSUE TITLE
`git-privacy redate`: check if `<startpoint>` is reachable from `HEAD`?

### ISSUE THREAD

**Issue by fapdash** [EMPRI-DEVOPS/git-privacy#34]
I think using git rev-list is a very elegant solution but I don't really like the user having to understand how rev-list actually works.
The intuitive understanding of `<startpoint>` actually being the startpoint of the redate process doesn't hold if `<starpoint>` is not reachable from the current `HEAD` as the redate process will start after their first shared ancestor.
I suggest at least asking the user if they really know what they are doing if such an input is given.

In egit-privacy I decided to not even offer the option to do a redate starting from such a startpoint as the resulting behavior would be confusing when triggered through the GUI.

@cburkert What do you think?

**Comment by fapdash** [comment]
My fault, rev-list works differently than I had thought. (I'm doing something else with jgit, so it's not comparable.)

**Comment by fapdash** [comment]
Reopening with examples:

### git rev-list referencing a commit that isn't reachable from current HEAD but has common ancestor

```
$ git checkout test
Switched to branch 'test'
$ git log --pretty=format:"%H"
4924b412ff859791ef743998dafa8ebe17664996
0b864e2e6c7a271c4154812524273552873a410a
69c81b3a452352189cbe832f046d088734fe12d6
da9b5b8bf55aa5f34b11e30679d8beecad458192
3bdd5aa60d2a014d1840632763e5b14307e5a9d5
$ git checkout master
Switched to branch 'master'
$ git log --pretty=format:"%H"
ee28e24bcb1793750d3aa823dac210bef8ba2002
85aec80fb9a77d69a680769dec194e859f238280
11241578af205b5d9afaf080086a436ffa72749d
95c1efa2a43a9c803f8bb65a76cfc473f73cd807
3bdd5aa60d2a014d1840632763e5b14307e5a9d5
$ git rev-list 4924b412ff859791ef743998dafa8ebe17664996..HEAD
ee28e24bcb1793750d3aa823dac210bef8ba2002
85aec80fb9a77d69a680769dec194e859f238280
11241578af205b5d9afaf080086a436ffa72749d
95c1efa2a43a9c803f8bb65a76cfc473f73cd807
```

rev-list returns all commits until the common ancestor.
I don't think this is what the user expects here.

### rev-list with a commit that isn't reachable from HEAD and has no common ancestor

```
$ git checkout --orphan version2
$ touch foo
$ git add foo
$ git commit -m "version 2"
$ git log
# head of version2: 3cca62980d686fab16da180af4d662a4a2794234
$ git checkout master
$ git rev-list 3cca62980d686fab16da180af4d662a4a2794234..HEAD
# returns ALL commits on master, starting from head going back to the initial commit
```

This is a corner case but at least [157 people](https://stackoverflow.com/a/5690048/4266296) wanted to have an orphan branch for some reason. :shrug:

**Comment by cburkert** [comment]
I see what you mean. This happens because `a..b` is a shorthand for `b ^a` which lists all that is reachable from `b` but _not_ from `a`, regardless of common ancestry.

You are right, that is unexpacted that the whole current branch is redated if `startpoint` is not reachable from `HEAD`.

As a fix, redate should reject a startpoint if it is not reachable from `HEAD`.
